

name: Cypress Tests

on:
  push:
    branches:
      - main  # or your primary branch
  pull_request:
    branches:
      - main  # or your primary branch

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]  # Use a current Node.js version

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests
        run: npx cypress run


